// Regenerates supabase/seed.sql and src/data/seedPlayers.ts from pickleball_players.xlsx.
// Run with: npm run seed:sql
import { readFileSync, writeFileSync } from 'node:fs';
import * as XLSX from 'xlsx';

const workbook = XLSX.read(readFileSync('pickleball_players.xlsx'));
const rows = XLSX.utils.sheet_to_json(workbook.Sheets.Players, { header: 1, blankrows: false });
const headerIndex = rows.findIndex((r) => r.includes('Name') && r.includes('Gender'));
const header = rows[headerIndex];
const col = (name) => header.indexOf(name);

const players = rows
  .slice(headerIndex + 1)
  .filter((r) => r[col('Name')])
  .map((r) => {
    const name = String(r[col('Name')]).trim();
    const gender = { Female: 'F', Male: 'M' }[String(r[col('Gender')]).trim()];
    const skill = { Advanced: 'A', Beginner: 'B' }[String(r[col('Skill Level')]).trim()];
    if (!gender || !skill) throw new Error(`Row for ${name} has an unknown gender or skill level.`);
    return { name, gender, skill };
  });

const sqlString = (s) => `'${s.replaceAll("'", "''")}'`;
writeFileSync(
  'supabase/seed.sql',
  `-- Generated by scripts/build-seed.mjs from pickleball_players.xlsx. Do not edit by hand.
insert into public.players (name, gender, skill) values
${players.map((p) => `  (${sqlString(p.name)}, '${p.gender}', '${p.skill}')`).join(',\n')}
on conflict (name) do update set gender = excluded.gender, skill = excluded.skill;
`,
);

writeFileSync(
  'src/data/seedPlayers.ts',
  `// Generated by scripts/build-seed.mjs from pickleball_players.xlsx. Do not edit by hand.
import type { Gender, Skill } from '../domain/types';

export const SEED_PLAYERS: ReadonlyArray<{ name: string; gender: Gender; skill: Skill }> = [
${players.map((p) => `  { name: ${JSON.stringify(p.name)}, gender: '${p.gender}', skill: '${p.skill}' },`).join('\n')}
];
`,
);

const count = (g, s) => players.filter((p) => p.gender === g && (!s || p.skill === s)).length;
console.log(`${players.length} players: women ${count('F')} (A ${count('F', 'A')}, B ${count('F', 'B')}), men ${count('M')} (A ${count('M', 'A')}, B ${count('M', 'B')})`);
